#!/usr/bin/env bash
echo "OOPS! This is a really bad script"
echo "It has been downloaded from the internet so it could be potentially ANYTHING!"
echo "           __"
echo "         _|  |_"
echo "       _|      |_"
echo "      |  _    _  |"
echo "      | |_|  |_| |"
echo "   _  |  _    _  |  _"
echo "  |_|_|_| |__| |_|_|_|"
echo "    |_|_        _|_|"
echo "      |_|      |_|"
echo ""
echo "Fortunately, this is just a demostration. A powerful one, I must say."
read -p "Press enter to exit..."
